# Generated by Django 4.0.2 on 2022-05-08 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_end_date_alter_job_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=150)),
                ('salary', models.FloatField(max_length=30)),
                ('image', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=350, null=True)),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=120)),
                ('skills', models.CharField(max_length=120)),
                ('creationdate', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.recruiter')),
            ],
        ),
    ]
